import type { Member, MemberStat } from "@/compartilhado/tipos/member.types";

export const MENTORS: Member[] = [
  {
    id: "ana-claudia",
    name: "Ana Cláudia do Carmo Cedraz",
    role: "Professora · Mentora",
    area: "Geografia, Sociologia & História",
    image: "/membros/Claudia.jpeg",
    imagePosition: "object-[center_30%]",
    iconName: "FlaskConical",
    color: "#F59E0B",
    quote: "A educação contextualizada é a base para o desenvolvimento social e humano.",
    tag: "Mentora · CECLOS 2026",
    category: "lideranca",
    num: "M-01",
  },
  {
    id: "victor",
    name: "Victor Montalvão Moreno",
    role: "Professor · Mentor",
    area: "Química, Biologia & Investigação",
    image: "/membros/Victor.png",
    imagePosition: "object-[center_35%]",
    iconName: "Cpu",
    color: "#F59E0B",
    quote: "No laboratório, a teoria ganha vida e o estudante assume o papel de pesquisador.",
    tag: "Mentor · CECLOS 2026",
    category: "lideranca",
    num: "M-02",
  },
  {
    id: "josue",
    name: "Josué Pimentel Dos Santos",
    role: "Professor · Mentor",
    area: "Matemática & Literatura de Cordel",
    image: "/membros/Josue.jpeg",
    imagePosition: "object-[center_30%]",
    iconName: "Telescope",
    color: "#F59E0B",
    quote: "A exatidão da matemática encontra a arte e a cultura popular no semiárido.",
    tag: "Mentor · CECLOS 2026",
    category: "lideranca",
    num: "M-03",
  },
];

export const MEMBERS: Member[] = [
  {
    id: "victor",
    name: "Prof. Victor Montalvão Moreno",
    role: "Orientador Principal",
    area: "Biologia · Química · Metodologia Científica",
    image: "/membros/Victor.png",
    imagePosition: "object-[center_35%]",
    iconName: "FlaskConical",
    color: "#F59E0B",
    quote: "A ciência começa com a pergunta certa e a coragem de buscar a resposta.",
    tag: "Orientador Principal · 2025",
    category: "lideranca",
    num: "01",
  },
  {
    id: "isaque",
    name: "Isaque Santos Bomfim",
    role: "Criador do Projeto & Desenvolvedor",
    area: "Engenharia de Software · Desenvolvimento Web",
    image: "/membros/Isaque.jpg",
    imagePosition: "object-[center_15%]",
    iconName: "Cpu",
    color: "#FDE68A",
    quote: "Código é a linguagem que transforma curiosidade em soluções reais.",
    tag: "Criador do Projeto · Dev · 2025",
    category: "lideranca",
    num: "02",
  },

  {
    id: "ana-claudia",
    name: "Ana Cláudia do Carmo Cedraz",
    role: "Professora · Mentora",
    area: "Geografia · Sociologia · História",
    image: "/membros/Claudia.jpeg",
    imagePosition: "object-[center_30%]",
    iconName: "Compass",
    color: "#F59E0B",
    quote: "A educação contextualizada é a base para o desenvolvimento social e humano.",
    tag: "Professora Orientadora · 2026",
    category: "lideranca",
    num: "03",
  },
  {
    id: "josue",
    name: "Josué Pimentel Dos Santos",
    role: "Professor · Mentor",
    area: "Matemática · Literatura de Cordel",
    image: "/membros/Josue.jpeg",
    imagePosition: "object-[center_30%]",
    iconName: "Telescope",
    color: "#FDE68A",
    quote: "A exatidão da matemática encontra a arte e a cultura popular no semiárido.",
    tag: "Professor Orientador · 2026",
    category: "lideranca",
    num: "05",
  },

  {
    id: "membro-1",
    name: "Laura Oliveira Santos",
    role: "Jovem Cientista",
    area: "Astronomia & Física",
    image: "/membros/Laura.jpeg",
    imagePosition: "object-[center_15%]",
    iconName: "Telescope",
    color: "#F59E0B",
    quote: "",
    tag: "Membro · 2026",
    category: "astronomia_fisica",
    num: "04",
  },
  {
    id: "membro-3",
    name: "Melissa Nascimento Barbosa",
    role: "Jovem Cientista",
    area: "Tecnologia & Robótica",
    image: "/membros/Melissa.png",
    imagePosition: "object-[center_15%]",
    iconName: "Code2",
    color: "#F59E0B",
    quote: "",
    tag: "Membro · 2026",
    category: "tecnologia_robotica",
    num: "06",
  },
  {
    id: "membro-5",
    name: "Ana Raquel Mascarenhas de Jesus",
    role: "Jovem Cientista",
    area: "Biotecnologia & Química",
    image: "/membros/Ana Raquel.png",
    imagePosition: "object-[center_20%]",
    iconName: "Microscope",
    color: "#F59E0B",
    quote: "",
    tag: "Membro · 2026",
    category: "biotec_quimica",
    num: "08",
  },
  {
    id: "membro-6",
    name: "Ana Beatriz Mascarenhas de Jesus",
    role: "Jovem Cientista",
    area: "Tecnologia & Robótica",
    image: "/membros/Beatriz.jpeg",
    imagePosition: "object-[center_15%]",
    iconName: "Cpu",
    color: "#FDE68A",
    quote: "",
    tag: "Membro · 2026",
    category: "tecnologia_robotica",
    num: "09",
  },
  {
    id: "membro-7",
    name: "João Pedro Oliveira Cardoso",
    role: "Jovem Cientista",
    area: "Terra & Exatas",
    image: "/membros/João.jpeg",
    imagePosition: "object-[center_15%]",
    iconName: "Globe2",
    color: "#F59E0B",
    quote: "",
    tag: "Membro · 2026",
    category: "terra_exatas",
    num: "10",
  },
  {
    id: "membro-8",
    name: "Raquely Maria Oliveira Santiago",
    role: "Jovem Cientista",
    area: "Astronomia & Física",
    image: "/membros/Raquelly.jpeg",
    imagePosition: "object-[center_15%]",
    iconName: "Telescope",
    color: "#FDE68A",
    quote: "",
    tag: "Membro · 2026",
    category: "astronomia_fisica",
    num: "11",
  },
  {
    id: "membro-9",
    name: "Ana Caroline Moraes Silva",
    role: "Jovem Cientista",
    area: "Biotecnologia & Química",
    image: "/membros/Ana Caroline.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Dna",
    color: "#F59E0B",
    quote: "",
    tag: "Membro · 2026",
    category: "biotec_quimica",
    num: "12",
  },
  {
    id: "membro-10",
    name: "Lorena Benvenuto Martins",
    role: "Jovem Cientista",
    area: "Tecnologia & Robótica",
    image: "/membros/Lorena.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Zap",
    color: "#FDE68A",
    quote: "",
    tag: "Membro · 2026",
    category: "tecnologia_robotica",
    num: "13",
  },
  {
    id: "membro-11",
    name: "Edmar de Souza Santana",
    role: "Jovem Cientista",
    area: "Terra & Exatas",
    image: "/membros/Edmar.png",
    imagePosition: "object-[center_18%]",
    iconName: "Compass",
    color: "#F59E0B",
    quote: "",
    tag: "Membro · 2026",
    category: "terra_exatas",
    num: "14",
  },
  {
    id: "membro-12",
    name: "Izabella Moreira Da Silva",
    role: "Jovem Cientista",
    area: "Biotecnologia & Química",
    image: "/membros/Izabella.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Atom",
    color: "#FDE68A",
    quote: "",
    tag: "Membro · 2026",
    category: "biotec_quimica",
    num: "15",
  },
  {
    id: "membro-13",
    name: "Gabriel Neri Almeida",
    role: "Jovem Cientista",
    area: "Terra & Exatas",
    image: "/membros/Gabriel.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Globe2",
    color: "#F59E0B",
    quote: "",
    tag: "Membro · 2026",
    category: "terra_exatas",
    num: "16",
  },
  {
    id: "membro-14",
    name: "Tarcisio Silva Oliveira",
    role: "Jovem Cientista",
    area: "Tecnologia & Robótica",
    image: "/membros/Tarcisio.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Code2",
    color: "#FDE68A",
    quote: "",
    tag: "Membro · 2026",
    category: "tecnologia_robotica",
    num: "17",
  },
  {
    id: "membro-15",
    name: "Alicia de Jesus Oliveira",
    role: "Jovem Cientista",
    area: "Biotecnologia & Química",
    image: "/membros/Alicia.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Microscope",
    color: "#F59E0B",
    quote: "",
    tag: "Membro · 2026",
    category: "biotec_quimica",
    num: "18",
  },
  {
    id: "membro-16",
    name: "Miguel dos Santos Silva",
    role: "Jovem Cientista",
    area: "Astronomia & Física",
    image: "/membros/Miguel.png",
    imagePosition: "object-[center_18%]",
    iconName: "Telescope",
    color: "#FDE68A",
    quote: "",
    tag: "Membro · 2026",
    category: "astronomia_fisica",
    num: "19",
  },
  {
    id: "membro-17",
    name: "André Moreira de Souza",
    role: "Jovem Cientista",
    area: "Tecnologia & Robótica",
    image: "/membros/ANDRE.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Dna",
    color: "#F59E0B",
    quote: "",
    tag: "Membro · 2026",
    category: "tecnologia_robotica",
    num: "20",
  },
  {
    id: "membro-18",
    name: "Lavyne Pereira Dos Santos Carvalho",
    role: "Jovem Cientista",
    area: "Terra & Exatas",
    image: "/membros/Lavine.png",
    imagePosition: "object-[center_18%]",
    iconName: "Zap",
    color: "#FDE68A",
    quote: "",
    tag: "Membro · 2026",
    category: "terra_exatas",
    num: "21",
  },
  {
    id: "membro-19",
    name: "Maria Laura Miranda Nascimento",
    role: "Jovem Cientista",
    area: "Terra & Exatas",
    image: "/membros/Laura Miranda.jpeg",
    imagePosition: "object-[center_20%]",
    iconName: "Compass",
    color: "#F59E0B",
    quote: "",
    tag: "Membro · 2026",
    category: "terra_exatas",
    num: "22",
  },

  {
    id: "membro-20",
    name: "Maria Eduarda dos Santos Pereira",
    role: "Jovem Cientista",
    area: "Terra & Exatas",
    image: "/membros/Eduarda.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Globe2",
    color: "#FDE68A",
    quote: "",
    tag: "Membro · 2026",
    category: "terra_exatas",
    num: "23",
  },
  {
    id: "membro-21",
    name: "Stefhane Oliveira Lima Matos",
    role: "Jovem Cientista",
    area: "Biotecnologia & Química",
    image: "/membros/Sthefane.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "FlaskConical",
    color: "#F59E0B",
    quote: "",
    tag: "Membro · 2026",
    category: "biotec_quimica",
    num: "24",
  },
  {
    id: "membro-22",
    name: "Rayla Santos Lima",
    role: "Jovem Cientista",
    area: "Terra & Exatas",
    image: "/membros/Rayla.png",
    iconName: "Cpu",
    color: "#FDE68A",
    quote: "",
    tag: "Membro · 2026",
    category: "terra_exatas",
    num: "25",
  },
  {
    id: "membro-24",
    name: "Beatriz Oliveira Santos",
    role: "Jovem Cientista",
    area: "Engenharia de Software & Dados",
    image: "/membros/Ana Beatriz.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Code2",
    color: "#FDE68A",
    quote: "A tecnologia como ferramenta de transformação social.",
    tag: "Membro · 2026",
    category: "tecnologia_robotica",
    num: "27",
  },
  {
    id: "membro-25",
    name: "Camila Beatriz Santana",
    role: "Jovem Cientista",
    area: "Biotecnologia & Microbiologia",
    image: "/membros/BEATRIZ02.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Microscope",
    color: "#F59E0B",
    quote: "A biologia nos ensina a observar o invisível e valorizar a vida.",
    tag: "Membro · 2026",
    category: "biotec_quimica",
    num: "28",
  },
  {
    id: "membro-26",
    name: "Raquel Lima Silva",
    role: "Jovem Cientista",
    area: "Física Experimental & Energia Solar",
    image: "/membros/RAQUEL.png",
    imagePosition: "object-[center_18%]",
    iconName: "Zap",
    color: "#FDE68A",
    quote: "Compreender as leis do universo para iluminar o futuro.",
    tag: "Membro · 2026",
    category: "astronomia_fisica",
    num: "29",
  },
  {
    id: "membro-27",
    name: "Lucas Gabriel Ramos",
    role: "Jovem Cientista",
    area: "Robótica & Automação de Sistemas",
    image: "/membros/Lucas.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Cpu",
    color: "#F59E0B",
    quote: "Construindo máquinas que auxiliam a pesquisa e a educação.",
    tag: "Membro · 2026",
    category: "tecnologia_robotica",
    num: "30",
  },

  {
    id: "membro-28",
    name: "Stefhane Lima Matos",
    role: "Jovem Cientista",
    area: "Química Ambiental & Tratamento de Água",
    image: "/membros/Sthefane.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "FlaskConical",
    color: "#FDE68A",
    quote: "Preservar os recursos hídricos é a missão mais urgente da nossa era.",
    tag: "Membro · 2026",
    category: "biotec_quimica",
    num: "31",
  },
  {
    id: "membro-29",
    name: "Kevilly Martins de Jesus",
    role: "Jovem Cientista",
    area: "Genética & Biologia Molecular",
    image: "/membros/Kevilly.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Dna",
    color: "#F59E0B",
    quote: "Desvendando os segredos do DNA para vencer desafios globais.",
    tag: "Membro · 2026",
    category: "biotec_quimica",
    num: "32",
  },
  {
    id: "membro-30",
    name: "Raquel Mascarenhas Ramos",
    role: "Jovem Cientista",
    area: "Astrofísica & Exploração Espacial",
    image: "/membros/RAQUEL02.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Telescope",
    color: "#FDE68A",
    quote: "Olhar para as estrelas nos lembra da nossa capacidade de sonhar longe.",
    tag: "Membro · 2026",
    category: "astronomia_fisica",
    num: "33",
  },

  {
    id: "membro-31",
    name: "Fábio dos Santos",
    role: "Jovem Cientista",
    area: "Matemática Aplicada & Modelagem",
    image: "/membros/Fabio.jpg",
    imagePosition: "object-[center_18%]",
    iconName: "Atom",
    color: "#F59E0B",
    quote: "A matemática é o mapa que guia toda grande descoberta.",
    tag: "Membro · 2026",
    category: "terra_exatas",
    num: "34",
  },
  {
    id: "membro-32",
    name: "Matheus Oliveira",
    role: "Jovem Cientista",
    area: "Sistemas Digitais & Inovação",
    image: "/membros/Matheus.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Globe2",
    color: "#FDE68A",
    quote: "Criatividade e lógica caminhando juntas na iniciação científica.",
    tag: "Membro · 2026",
    category: "tecnologia_robotica",
    num: "35",
  },
  {
    id: "membro-33",
    name: "Robson da Silva",
    role: "Jovem Cientista",
    area: "Agronomia & Conservação Ambiental",
    image: "/membros/Robson.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Globe2",
    color: "#F59E0B",
    quote: "A terra do semiárido tem força, ciência e futuro.",
    tag: "Membro · 2026",
    category: "terra_exatas",
    num: "36",
  },
  {
    id: "membro-34",
    name: "Thiago Santana",
    role: "Jovem Cientista",
    area: "Física & Energias Renováveis",
    image: "/membros/Thiago.jpeg",
    imagePosition: "object-[center_18%]",
    iconName: "Zap",
    color: "#FDE68A",
    quote: "Pesquisar é descobrir o poder que temos de transformar a realidade.",
    tag: "Membro · 2026",
    category: "astronomia_fisica",
    num: "37",
  },
];

export const MEMBER_STATS: MemberStat[] = [
  { label: "Integrantes Ativos", value: "35" },
  { label: "Áreas de Investigação", value: "04" },
  { label: "Projetos em Curso", value: "16+" },
  { label: "Fundado em", value: "2025" },
];
